# Generated by Django 3.2.4 on 2024-02-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0002_accounttype_administeredancillarycare_administeredancillarycarebillableitem_administeredancillarycar'),
    ]

    operations = [
    ]
