# Generated by Django 3.2.4 on 2024-02-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0003_auto_20240201_2128'),
    ]

    operations = [
    ]
