# Generated by Django 3.2.4 on 2024-02-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0004_auto_20240201_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicereceipt',
            options={'managed': True},
        ),
    ]
