# Generated by Django 3.2.4 on 2024-02-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0006_auto_20240202_1318'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='invoicereceipt',
    #         name='branch',
    #         field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Registry.branch'),
    #     ),
    # ]
