# Generated by Django 3.2.4 on 2024-02-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0009_auto_20240202_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Registry.bank'),
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='bank_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='bank_transaction_id',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='currency_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),  
        migrations.AddField(
            model_name='invoicereceipt',
            name='paymentStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
