# Generated by Django 3.2.4 on 2024-02-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0010_auto_20240202_1622'),
    ]

    operations = [

    ]
