# Generated by Django 3.2.4 on 2024-02-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0011_auto_20240204_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature_images/'),
        ),
    ]
