# Generated by Django 3.2.4 on 2024-02-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0012_auto_20240204_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicereceipt',
            name='prn',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
